/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vistas;

import estructuras.*;
import javax.swing.JOptionPane;

/**
 *
 * @author desandlope0
 */
public class ArregloDinamicoVentana extends javax.swing.JFrame {

    /**
     * Creates new form ArregloDinamicoView
     */
    GestorArregloDinamico gestor = new GestorArregloDinamico();

    public ArregloDinamicoVentana() {
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitulo = new javax.swing.JLabel();
        lblTituloResultados = new javax.swing.JLabel();
        scrResultados = new javax.swing.JScrollPane();
        txtResultados = new javax.swing.JTextArea();
        pnlGestionArregloDinamico = new javax.swing.JPanel();
        lblTamanioArreglo = new javax.swing.JLabel();
        txtTamanio = new javax.swing.JTextField();
        txtIndice = new javax.swing.JTextField();
        btnAgregar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        btnAsignar = new javax.swing.JButton();
        lblElemento = new javax.swing.JLabel();
        lblIndice = new javax.swing.JLabel();
        btnBuscar = new javax.swing.JButton();
        txtElemento = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblTitulo.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblTitulo.setText("ET01 - Arreglos Dinámicos");

        lblTituloResultados.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        lblTituloResultados.setText("Visualización de resutados");

        txtResultados.setColumns(20);
        txtResultados.setRows(5);
        scrResultados.setViewportView(txtResultados);

        pnlGestionArregloDinamico.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Gestión del Arreglo", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11))); // NOI18N

        lblTamanioArreglo.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        lblTamanioArreglo.setText("Tamaño Inicial");

        txtTamanio.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        txtTamanio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTamanioActionPerformed(evt);
            }
        });

        txtIndice.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N

        btnAgregar.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        btnAgregar.setText("Agregar");
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });

        btnEliminar.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        btnAsignar.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        btnAsignar.setText("Asignar");
        btnAsignar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAsignarActionPerformed(evt);
            }
        });

        lblElemento.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        lblElemento.setText("Elemento ");

        lblIndice.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        lblIndice.setText("Índice");

        btnBuscar.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        txtElemento.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N

        javax.swing.GroupLayout pnlGestionArregloDinamicoLayout = new javax.swing.GroupLayout(pnlGestionArregloDinamico);
        pnlGestionArregloDinamico.setLayout(pnlGestionArregloDinamicoLayout);
        pnlGestionArregloDinamicoLayout.setHorizontalGroup(
            pnlGestionArregloDinamicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlGestionArregloDinamicoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlGestionArregloDinamicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblTamanioArreglo)
                    .addComponent(btnEliminar)
                    .addComponent(lblIndice, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                .addComponent(btnAgregar)
                .addGap(36, 36, 36)
                .addComponent(btnBuscar)
                .addGap(38, 38, 38))
            .addGroup(pnlGestionArregloDinamicoLayout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(lblElemento)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlGestionArregloDinamicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlGestionArregloDinamicoLayout.createSequentialGroup()
                        .addGroup(pnlGestionArregloDinamicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtIndice, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(pnlGestionArregloDinamicoLayout.createSequentialGroup()
                                .addComponent(txtTamanio, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnAsignar)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(pnlGestionArregloDinamicoLayout.createSequentialGroup()
                        .addComponent(txtElemento)
                        .addContainerGap())))
        );
        pnlGestionArregloDinamicoLayout.setVerticalGroup(
            pnlGestionArregloDinamicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlGestionArregloDinamicoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlGestionArregloDinamicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtTamanio)
                    .addGroup(pnlGestionArregloDinamicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblTamanioArreglo)
                        .addComponent(btnAsignar)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlGestionArregloDinamicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblElemento)
                    .addComponent(txtElemento, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(7, 7, 7)
                .addGroup(pnlGestionArregloDinamicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtIndice, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblIndice, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(pnlGestionArregloDinamicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnBuscar)
                    .addGroup(pnlGestionArregloDinamicoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnAgregar)
                        .addComponent(btnEliminar)))
                .addGap(14, 14, 14))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblTituloResultados)
                            .addComponent(pnlGestionArregloDinamico, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(scrResultados)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(73, 73, 73)
                        .addComponent(lblTitulo)))
                .addContainerGap(19, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTitulo)
                .addGap(18, 18, 18)
                .addComponent(pnlGestionArregloDinamico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblTituloResultados)
                .addGap(11, 11, 11)
                .addComponent(scrResultados, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtTamanioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTamanioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTamanioActionPerformed

    private void btnAsignarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAsignarActionPerformed
        try {
            int tamanio = Integer.parseInt(txtTamanio.getText());
            gestor.tamanioDinamico(tamanio);
            txtResultados.setText(gestor.visualizar());
        } catch (NumberFormatException numberFormatException) {
            JOptionPane.showMessageDialog(null, "Debe ingresar un numero entero en el tamaño");
            txtTamanio.setText("");
        }
    }//GEN-LAST:event_btnAsignarActionPerformed

    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
        try {
            int elemento = Integer.parseInt(txtElemento.getText());
            int indice = Integer.parseInt(txtIndice.getText());

            if (indice >= 0) {
                gestor.agregar(indice, elemento);
                txtResultados.setText(gestor.visualizar());
            } else {
                throw new Exception();
            }
        } catch (NumberFormatException numberFormatException) {
            JOptionPane.showMessageDialog(null, "Debe ingresar un numero entero en el indice y elemento");
            txtElemento.setText("");
            txtIndice.setText("");
        } catch (Exception exception) {
            JOptionPane.showMessageDialog(null, "El indice debe ser mayor igual que 0 y menor que el tamaño");
            txtElemento.setText("");
            txtIndice.setText("");

        }
    }//GEN-LAST:event_btnAgregarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        try {
            int indice = Integer.parseInt(txtIndice.getText());
            if (indice >= 0) {
                gestor.eliminar(indice);
                txtResultados.setText(gestor.visualizar());
            } else {
                throw new Exception();
            }
        } catch (NumberFormatException numberFormatException) {
            JOptionPane.showMessageDialog(null, "Debe ingresar un numero entero en el indice y elemento");
            txtElemento.setText("");
            txtIndice.setText("");
        } catch (Exception exception) {
            JOptionPane.showMessageDialog(null, "El indice debe ser mayor igual que 0 y menor que el tamaño");
            txtElemento.setText("");
            txtIndice.setText("");

        }
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        int elemento = Integer.parseInt(txtElemento.getText());
        gestor.busqueda(elemento);
        txtResultados.setText(gestor.visualizar());
    }//GEN-LAST:event_btnBuscarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Metal".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ArregloDinamicoVentana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ArregloDinamicoVentana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ArregloDinamicoVentana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ArregloDinamicoVentana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ArregloDinamicoVentana().setVisible(true);

            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnAsignar;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JLabel lblElemento;
    private javax.swing.JLabel lblIndice;
    private javax.swing.JLabel lblTamanioArreglo;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JLabel lblTituloResultados;
    private javax.swing.JPanel pnlGestionArregloDinamico;
    private javax.swing.JScrollPane scrResultados;
    private javax.swing.JTextField txtElemento;
    private javax.swing.JTextField txtIndice;
    private javax.swing.JTextArea txtResultados;
    private javax.swing.JTextField txtTamanio;
    // End of variables declaration//GEN-END:variables
}
